# Generated by Django 6.0.4 on 2026-04-20 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="城市名称"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "城市",
                "verbose_name_plural": "城市管理",
            },
        ),
        migrations.CreateModel(
            name="Datacenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="机房名称")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hosts.city",
                        verbose_name="所属城市",
                    ),
                ),
            ],
            options={
                "verbose_name": "机房",
                "verbose_name_plural": "机房管理",
            },
        ),
        migrations.CreateModel(
            name="Host",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hostname",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="主机名"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(unique=True, verbose_name="IP地址"),
                ),
                ("_root_password", models.BinaryField(verbose_name="root密码")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否活跃"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "datacenter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hosts.datacenter",
                        verbose_name="所属机房",
                    ),
                ),
            ],
            options={
                "verbose_name": "主机",
                "verbose_name_plural": "主机管理",
            },
        ),
        migrations.CreateModel(
            name="HostCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(verbose_name="主机数量")),
                ("date", models.DateField(auto_now_add=True, verbose_name="统计日期")),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hosts.city",
                        verbose_name="城市",
                    ),
                ),
                (
                    "datacenter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hosts.datacenter",
                        verbose_name="机房",
                    ),
                ),
            ],
            options={
                "verbose_name": "主机统计",
                "verbose_name_plural": "主机统计管理",
            },
        ),
        migrations.AddConstraint(
            model_name="datacenter",
            constraint=models.UniqueConstraint(
                fields=("name", "city"), name="unique_datacenter_in_city"
            ),
        ),
        migrations.AddConstraint(
            model_name="hostcount",
            constraint=models.UniqueConstraint(
                fields=("city", "datacenter", "date"), name="unique_host_count"
            ),
        ),
    ]
